cargo-features = ["codegen-backend"]

[package]
name = "pittacia"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
dialoguer = "0.11.0"
regex = "1.10.4"

[profile.dev]
codegen-backend = "cranelift"
